name: Build and Deploy Bun app to Azure Web App

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    docker:
        runs-on: [self-hosted, ARM64]
        steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GHCR_PAT }}
              
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              push: true
              tags: ghcr.io/${{ github.repository }}

    deploy:
        runs-on: [self-hosted, ARM64]
        needs: docker
        environment:
            name: 'production'
            url: hansika.azurewebsites.net

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            
          - name: Login to Azure
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
              
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'hansika'
              package: '.'
              slot-name: 'production'
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: 'ghcr.io/jamieeeeeeeeeeeeeeee/hansika:latest'